{% set name = "geedim" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geedim-{{ version }}.tar.gz
  sha256: 1b25a40e10212910e5905e34bf5f22dafd6fbc13d80d6af2ca085b0336661249

build:
  entry_points:
    - geedim=geedim.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - pandas >= 1.1
  run:
    - python >=3.6
    - numpy >= 1.19
    - rasterio >= 1.1
    - click >= 8
    - tqdm >= 4.6
    - earthengine-api >= 0.1.2
    - requests >= 2.2
    - tabulate >= 0.8
test:
  imports:
    - geedim
  commands:
    - geedim --help

about:
  home: https://github.com/dugalh/geedim
  summary: Google Earth Engine image download
  license: Apache-2.0
  license_file: LICENSE
  description: |
    geedim provides a command line interface and API for searching GEE images
    by date, region, and cloud/shadow statistics. It optionally performs
    cloud/shadow masking, and cloud-free compositing. Images and composites can
    be downloaded (without size limits and including metadata), or exported to
    Google Drive.

extra:
  recipe-maintainers:
    - dugalh
