# Config file for conda package
#
#  To build, install & remove the development version:
#    git clone git+https://github.com/dugalh/geedim.git
#    conda build .
#    conda install -c conda-forge --use-local geedim
#    conda remove -c conda-forge --use-local geedim

package:
  name: geedim
  version: 0.1.0

source:
  git_url: https://github.com/dugalh/geedim.git

requirements:
  run:
    - python >=3.8
    - pandas >=1.3
    - earthengine-api >=0.1.2
    - requests

build:
  number: 0
  noarch: python
  script: pip install -e .

about:
  home: https://github.com/dugalh/geedim
  license: Apache-2.0
