# Test publishing to, and installing and running with Test PyPI

name: Install & test PyPI package
on:
  workflow_dispatch:

jobs:
  # Install geedim from Test PyPI and test CLI
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
    steps:
      - uses: actions/checkout@v2   # checkout repository with test data
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install geedim from Test PyPI
        run: |
          python -m pip install --upgrade pip
          python -m pip install geedim
      - name: Test geedim CLI
        timeout-minutes: 5
        env:
          EE_SERVICE_ACC_PRIVATE_KEY: ${{ secrets.EE_SERVICE_ACC_PRIVATE_KEY }}
        run: |
          geedim --help
          geedim search -c landsat8_c2_l2 -s 2019-02-01 -e 2019-03-01 --bbox 23 -33 23.2 -33.2 composite -cm q_mosaic --mask download --scale 30 --crs EPSG:3857 -o
          pwd
          ls -R
