# Build geedim package and publish to PyPI

name: Publish
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Build package
      run: python -m build
#     - name: Publish package to TestPyPI
#       run: python -m twine upload -u __token__ -p ${{ secrets.TEST_PYPI_TOKEN }} --repository testpypi dist/*
#    - name: Publish package to TestPyPI
#      uses: pypa/gh-action-pypi-publish@release/v1
#      with:
#          user: __token__
#          password: ${{ secrets.TEST_PYPI_TOKEN }}
#          repository_url: https://test.pypi.org/
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
